[project]
name = "screenshot-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyside6>=6.10.2",
    "questionary>=2.1.1",
    "rumps>=0.4.0",
    "watchdog>=6.0.0",
]
